# Generated by Django 2.1.5 on 2019-03-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Google_crawl',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name', max_length=20)),
                ('employee_number', models.CharField(help_text='Employee Number ex) KR62111', max_length=12)),
                ('team_name', models.CharField(choices=[('', 'Choose your team...'), ('1', 'NSML'), ('2', 'AI Production'), ('3', 'AI Research'), ('4', 'Biz AI'), ('5', 'OCR'), ('6', 'Speech'), ('7', 'Voice'), ('8', 'Vision'), ('9', 'Data & Connection'), ('10', 'NSML Competition TF'), ('11', 'DUET TF'), ('12', 'Pasha TF')], help_text='- TEAM NAME -', max_length=20)),
                ('download_type', models.CharField(choices=[('0', 'JPG_ONLY'), ('1', 'URL+Meta')], max_length=20)),
                ('crawl_info', models.TextField(help_text='데이터가 어떤 연구 / 프로젝트에 사용 될지 말씀해주세요', max_length=200)),
                ('keyword', models.CharField(help_text='keyword to crawl images from google ex) dog', max_length=20)),
                ('max_num', models.IntegerField(help_text='Maximum number of images to download ex) 10000')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
