# Generated by Django 2.1.7 on 2019-03-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='flickr_crawl',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('employee_number', models.CharField(help_text='ex) KR62111', max_length=12)),
                ('team_name', models.CharField(choices=[('', 'Choose your team...'), ('NSML', 'NSML'), ('AI Production', 'AI Production'), ('AI Research', 'AI Research'), ('Biz AI', 'Biz AI'), ('OCR', 'OCR'), ('Speech', 'Speech'), ('Voice', 'Voice'), ('Vision', 'Vision'), ('Data & Connection', 'Data & Connection'), ('NSML Competition TF', 'NSML Competition TF'), ('DUET TF', 'DUET TF'), ('Pasha TF', 'Pasha TF')], help_text='- TEAM NAME -', max_length=20)),
                ('crawl_info', models.TextField(help_text='Simply write down what research the data will be used in.', max_length=200)),
                ('keyword', models.CharField(help_text='keyword to crawl images from google ex) dog', max_length=50)),
                ('max_num', models.IntegerField(help_text='Number of images to download ex) 10000')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='instagram_crawler',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('employee_number', models.CharField(help_text='ex) KR62111', max_length=12)),
                ('team_name', models.CharField(choices=[('', 'Choose your team...'), ('NSML', 'NSML'), ('AI Production', 'AI Production'), ('AI Research', 'AI Research'), ('Biz AI', 'Biz AI'), ('OCR', 'OCR'), ('Speech', 'Speech'), ('Voice', 'Voice'), ('Vision', 'Vision'), ('Data & Connection', 'Data & Connection'), ('NSML Competition TF', 'NSML Competition TF'), ('DUET TF', 'DUET TF'), ('Pasha TF', 'Pasha TF')], help_text='- TEAM NAME -', max_length=20)),
                ('download_type', models.CharField(choices=[('0', 'JPG_ONLY'), ('1', 'URL+Meta')], max_length=20)),
                ('crawl_info', models.TextField(help_text='Simply write down what research the data will be used in.', max_length=200)),
                ('keyword', models.CharField(help_text='keyword to crawl images from google ex) dog', max_length=50)),
                ('max_num', models.IntegerField(help_text='Number of images to download ex) 10000')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='google_crawl',
            name='crawl_info',
            field=models.TextField(help_text='Simply write down what research the data will be used in.', max_length=200),
        ),
        migrations.AlterField(
            model_name='google_crawl',
            name='employee_number',
            field=models.CharField(help_text='ex) KR62111', max_length=12),
        ),
        migrations.AlterField(
            model_name='google_crawl',
            name='keyword',
            field=models.CharField(help_text='keyword to crawl images from google ex) dog', max_length=50),
        ),
        migrations.AlterField(
            model_name='google_crawl',
            name='max_num',
            field=models.IntegerField(help_text='Number of images to download ex) 10000'),
        ),
        migrations.AlterField(
            model_name='google_crawl',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='google_crawl',
            name='team_name',
            field=models.CharField(choices=[('', 'Choose your team...'), ('NSML', 'NSML'), ('AI Production', 'AI Production'), ('AI Research', 'AI Research'), ('Biz AI', 'Biz AI'), ('OCR', 'OCR'), ('Speech', 'Speech'), ('Voice', 'Voice'), ('Vision', 'Vision'), ('Data & Connection', 'Data & Connection'), ('NSML Competition TF', 'NSML Competition TF'), ('DUET TF', 'DUET TF'), ('Pasha TF', 'Pasha TF')], help_text='- TEAM NAME -', max_length=20),
        ),
    ]
