# Generated by Django 2.1.7 on 2019-03-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_auto_20190310_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='google_crawl',
            name='keyword',
            field=models.CharField(help_text='keyword to crawl images from google. If the keyword includes a space bar, mark it as underbar. ex) green_snake', max_length=50),
        ),
        migrations.AlterField(
            model_name='google_crawl',
            name='max_num',
            field=models.CharField(help_text='Number of images to download ex) 10000', max_length=50),
        ),
    ]
