# Generated by Django 2.1.7 on 2019-03-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_auto_20190314_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flickr_crawl',
            name='keyword',
            field=models.CharField(help_text='keyword to crawl images from google. 500이상 입력해주세요. ex) dog', max_length=100),
        ),
        migrations.AlterField(
            model_name='google_crawl',
            name='download_type',
            field=models.CharField(choices=[('0', 'Image Only'), ('1', 'JSON with meta information')], max_length=20),
        ),
        migrations.AlterField(
            model_name='google_crawl',
            name='keyword',
            field=models.CharField(help_text='keyword to crawl images from google. If the keyword includes a space bar, mark it as underbar. ex) green_snake', max_length=100),
        ),
        migrations.AlterField(
            model_name='google_crawl',
            name='max_num',
            field=models.CharField(help_text='Number of images to download. 500이상 입력해주세요. ex) 10000', max_length=50),
        ),
        migrations.AlterField(
            model_name='instagram_crawler',
            name='download_type',
            field=models.CharField(choices=[('0', 'Image Only'), ('1', 'JSON with meta information')], max_length=20),
        ),
        migrations.AlterField(
            model_name='instagram_crawler',
            name='keyword',
            field=models.CharField(help_text='keyword to crawl images from google ex) dog', max_length=100),
        ),
    ]
