# Generated by Django 2.1.7 on 2019-03-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_auto_20190317_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flickr_crawl',
            name='crawl_info',
            field=models.TextField(help_text='Simply write down what research the data will be used in.', max_length=100),
        ),
        migrations.AlterField(
            model_name='google_crawl',
            name='crawl_info',
            field=models.TextField(help_text='Simply write down what research the data will be used in.', max_length=100),
        ),
        migrations.AlterField(
            model_name='instagram_crawler',
            name='crawl_info',
            field=models.TextField(help_text='Simply write down what research the data will be used in.', max_length=100),
        ),
    ]
