# Generated by Django 2.1.7 on 2019-03-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0006_auto_20190317_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagram_crawler',
            name='max_num',
        ),
        migrations.AddField(
            model_name='instagram_crawler',
            name='num',
            field=models.IntegerField(default=500, help_text='Number of images to download. All keywords can be crawled by the same number. Please enter only one number. ex) 500'),
        ),
        migrations.AlterField(
            model_name='flickr_crawl',
            name='keyword',
            field=models.CharField(help_text='Please enter the keyword for the data you want to crawl. You can enter multiple keyword using a comma. ex) green snake, pug', max_length=100),
        ),
        migrations.AlterField(
            model_name='flickr_crawl',
            name='max_num',
            field=models.CharField(help_text='Number of images to download. Please enter 500 units. Please enter max num value by the number of keywords you entered. ex) 500, 1000', max_length=50),
        ),
        migrations.AlterField(
            model_name='google_crawl',
            name='keyword',
            field=models.CharField(help_text='Please enter the keyword for the data you want to crawl. You can enter multiple keyword using a comma. ex) green snake, pug', max_length=100),
        ),
        migrations.AlterField(
            model_name='google_crawl',
            name='max_num',
            field=models.CharField(help_text='Number of images to download. Please enter max num value by the number of keywords you entered. ex) 500, 1000', max_length=50),
        ),
        migrations.AlterField(
            model_name='instagram_crawler',
            name='keyword',
            field=models.CharField(help_text='Please enter the keyword for the data you want to crawl. You can enter up to two keywords using space. ex) lovestagram greensnake', max_length=100),
        ),
    ]
