# Generated by Django 2.1.7 on 2019-03-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0007_auto_20190324_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagram_crawler',
            name='num',
            field=models.IntegerField(help_text='Number of images to download. All keywords can be crawled by the same number. Please enter only one number. ex) 500'),
        ),
    ]
