# Generated by Django 2.1.5 on 2019-05-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0008_auto_20190324_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagram_crawler',
            name='keyword',
            field=models.CharField(help_text='Please enter the keyword for the data you want to crawl using space. ex) lovestagram greensnake', max_length=100),
        ),
    ]
