# Generated by Django 2.1.5 on 2019-05-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='webdoc',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('employee_number', models.CharField(help_text='ex) KR62111', max_length=12)),
                ('team_name', models.CharField(choices=[('', 'Choose your team...'), ('NSML', 'NSML'), ('AI Production', 'AI Production'), ('AI Research', 'AI Research'), ('Biz AI', 'Biz AI'), ('OCR', 'OCR'), ('Speech', 'Speech'), ('Voice', 'Voice'), ('Vision', 'Vision'), ('Data & Connection', 'Data & Connection'), ('NSML Competition TF', 'NSML Competition TF'), ('DUET TF', 'DUET TF'), ('Pasha TF', 'Pasha TF')], help_text='- TEAM NAME -', max_length=20)),
                ('domain_for_data', models.CharField(choices=[('', 'please Choose Domain for crawl...'), ('instagram', 'instagram'), ('flickr', 'flickr'), ('500px', '500px'), ('facebook', 'facebook')], help_text=' - DOMAIN -', max_length=20)),
                ('crawl_information', models.TextField(help_text='Simply write down what research the data will be used in, please :)', max_length=100)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
